name: Tex Compile

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile tex files
        run: |
          chmod +x scripts/build-tex.sh
          scripts/build-tex.sh